### ISSUE TITLE
Fixes Products

### ISSUE THREAD

**Issue by so2niko** [anogire/what-ui-store#11]
- [x] Проверять не наличие этого аттрибута, а то, что в нем записано. 

https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.controller.js#L39-L44

__________________________________________________

- [x] Название не соответствует возвращаемому значению. Может переименовать его в isSearchedProduct?
https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.model.js#L102

_________________________________________________________

- [x] Переписать без тернарника возможно? В целом это условие повторяется минимум трижды. Может стоит вынести его в отдельный метод?
https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.model.js#L110

____________________________________________________

- [x] К этому свойству можно и без квадратных скобок добраться
https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.model.js#L80
https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.model.js#L92-L95
https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.model.js#L107-L108
https://github.com/anogire/what-ui-store/blob/8528b0a10278ef36d3d9339df8ad5bbc32867371/app/products/products.model.js#L114
____________________________________________________

**Comment by anogire** [comment]
fixed
